# File: cluster.yaml
# ─────────────────────────────────────────────
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: E-commerce-prod    # ← give your cluster a name
  region: us-east-1            # ← your AWS region
  version: '1.34'

managedNodeGroups:
  - name: prod-workers
    instanceType: t3.small    # ← VM size (2 CPU, 4GB RAM each)
    minSize: 2
    maxSize: 10
    desiredCapacity: 3         # start with 3 nodes
    privateNetworking: true    # nodes in private subnets (safer)

iam:
  withOIDC: true               # needed for ALB + ECR access

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
